/**
 * @description: 锅底
 * @param: g_Type-->1
 */
let guodi = {
    "msg": "成功",
    "value": {
        "pageNum": 1,
        "pageSize": 100,
        "total": 9,
        "pages": 1,
        "list": [
            {
                "id": 368,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "海底捞新一代番茄火锅",
                "menuName": null,
                "dishTag": "一定要喝汤的番茄火锅",
                "dishDesc": "选用新品种的熟成沙瓤番茄，皮薄肉厚，番茄口感更绵密，汁水充盈，酸甜味更佳，锅底中番茄添加量更多！",
                "imgUrl": "https://website.hdlcdns.com/website/image/0908ca0d8e164761b795fe8e83764fad-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 41,
                "createdBy": null,
                "coverArea": "全国覆盖",
                "createdTime": 1600324868043,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1654840927075
            },
            {
                "id": 3307,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "经典麻辣火锅",
                "menuName": null,
                "dishTag": "慢火熬煮4小时的经典麻辣锅底",
                "dishDesc": "选用精选牛油与青花椒和红花椒、及多种辣椒慢火熬煮而成。锅底油色红亮、汤味醇厚，越煮越香不变味。搭配蒜泥香油味碟，这样吃才地道！",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/815c991fcb59421e9f425805a431df55-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 61,
                "createdBy": null,
                "coverArea": "全国覆盖",
                "createdTime": 1602222608385,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1638415713442
            },
            {
                "id": 3493,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "清油麻辣火锅",
                "menuName": null,
                "dishTag": "植物油炒制，香辣浓郁不油腻",
                "dishDesc": "严选花椒、辣椒、香辛料原料，地道川味火锅；传统工艺发酵豆瓣；汤底色泽鲜红，口味香辣浓郁；推荐搭配经典毛肚、鸭肠、牛肉、羊肉类产品。",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/c746b391bc2545ea8e71033e4d12549a-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 63,
                "createdBy": null,
                "coverArea": "全国覆盖",
                "createdTime": 1602820076917,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1638415724725
            },
            {
                "id": 3494,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "三鲜火锅",
                "menuName": null,
                "dishTag": "色泽纯正，口感鲜香浓郁",
                "dishDesc": "选用现代工艺萃取的肉类浓缩骨汤为汤底；可根据喜好搭配不同的特色味碟、推荐搭配涮食海鲜类及素食类食材。",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/34bb9afa210d4848808e3c0317bc60c7-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 64,
                "createdBy": null,
                "coverArea": "全国覆盖",
                "createdTime": 1602820262119,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1638415732646
            },
            {
                "id": 3495,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "猪肚鸡火锅",
                "menuName": null,
                "dishTag": "汤头乳白、鲜香浓郁",
                "dishDesc": "精选猪肚、三黄鸡、经慢火熬制的风味猪肚汤料包，鲜香浓郁、椒香扑鼻；推荐搭配涮素食食材。",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/5897814a4ed140a087e7cc5c4354e69c-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 65,
                "createdBy": null,
                "coverArea": "部分地区覆盖",
                "createdTime": 1602820303171,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1642141257113
            },
            {
                "id": 7634,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "姬松茸菌汤火锅",
                "menuName": null,
                "dishTag": "菌汤看得见，浓香又鲜美。",
                "dishDesc": "菌菇看得见，汤鲜味美；菌香浓郁、爽口；推荐搭配涮食菌菇类食材。",
                "imgUrl": "https://website.hdlcdns.com/website/image/8e61d8478d1d4356809eadc80f0d1f96-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 73,
                "createdBy": null,
                "coverArea": "部分区域可售",
                "createdTime": 1638427471630,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644386680759
            },
            {
                "id": 7676,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "真香锅",
                "menuName": null,
                "dishTag": "汤底鲜香，麻辣适中，油脂香味突出， 味道清爽不油腻。",
                "dishDesc": "采用植物油和少量牛油混合，并添加多种香辛料、辣椒、花椒混合炒制，汤底鲜香、麻辣适中、油脂香味突出，味道清爽不油腻。推荐搭配毛肚、牛肉、羊肉涮煮。",
                "imgUrl": "https://website.hdlcdns.com/website/image/66d9d0cff0b245308ec1f9fc4808bdc3-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 75,
                "createdBy": null,
                "coverArea": "全国覆盖",
                "createdTime": 1641874151691,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1647933400839
            },
            {
                "id": 7744,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "牛肉汤火锅",
                "menuName": null,
                "dishTag": "鲜香味美，牛肉骨汤风味浓郁。",
                "dishDesc": "使用萃取工艺，将鸡骨、牛骨浓缩为风味骨汤；搭配大块牛肉和新鲜白萝卜，鲜香味美，牛肉汤风味浓郁。",
                "imgUrl": "https://website.hdlcdns.com/website/image/13b25c5d78954a29aedb2b2e01c4f812-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 76,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1648451706731,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1648471558357
            },
            {
                "id": 8240,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "海底捞泡菜鸭锅",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "酸辣突出，泡菜香味浓郁",
                "imgUrl": "https://website.hdlcdns.com/website/image/b391ba1b4f3048c49a41e21d0fdb4c04-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 79,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1666930702596,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1666930702595
            }
        ]
    },
    "rc": 100000,
    "success": true
};

let sql = "insert into goods (g_id, g_dishName, g_dishDesc, g_imgUrl, g_createdTime, g_publishTime, g_Type,g_shopid) values ";
// sql = sql + "(" + guodi.value.list[0].id +",'"+guodi.value.list[0].dishName+"','"+guodi.value.list[0].dishDesc+"','"+guodi.value.list[0].imgUrl+"',"+guodi.value.list[0].createdTime+","+guodi.value.list[0].publishTime+","+"1"+","+"1"+"),";

let i=0;
for(;i<guodi.value.list.length;i++){
    sql = sql + "(" + i +",'"+guodi.value.list[i].dishName+"','"+guodi.value.list[i].dishDesc+"','"+guodi.value.list[i].imgUrl+"',"+guodi.value.list[i].createdTime+","+guodi.value.list[i].publishTime+","+"1"+","+"1"+"),";
}
console.log(sql);