/**
 * @description: 涮菜
 * @param: g_Type-->2
 */
let shuancai = {
    "msg": "成功",
    "value": {
        "pageNum": 1,
        "pageSize": 100,
        "total": 9,
        "pages": 1,
        "list": [
            {
                "id": 8242,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "捞派魔芋素毛肚",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "海底捞全新推出素毛肚，从此“毛肚”放肆吃，口感Q弹，8秒就涮好。",
                "imgUrl": "https://website.hdlcdns.com/website/image/22b537a88f814392b4b24202a8cb3eb1-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 85,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667194463766,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667194535106
            },
            {
                "id": 8243,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "过足肉瘾大块羊肋排",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "只选用12个月以内的羔羊肋排部位，不拆骨白卤入味，根根贴骨肉，更香更过瘾。",
                "imgUrl": "https://website.hdlcdns.com/website/image/790f515ed3494c1db21cd885dc6a9eb3-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 86,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667194565220,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667194565219
            }, 
            {
                "id": 8244,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "海底捞咯吱咯吱贡菜丸子",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "选用优质猪腿、鸡腿肉，搭配干贡菜手工制作肉丸，贡菜的爽口，咯吱咯吱，香而不腻。",
                "imgUrl": "https://website.hdlcdns.com/website/image/594e681ab7854d349069919b7e825ce1-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 87,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667194633475,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667194633474
            },
            {
                "id": 8245,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "嫩滑黑鱼片",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "选用大片黑鱼肉，肉质鲜嫩，口感更弹韧。",
                "imgUrl": "https://website.hdlcdns.com/website/image/08687dbca37e48b1906f669dcc659c5b-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 88,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667194678299,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667194678297
            },
            {
                "id": 8246,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "捞派生鸭血",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "低温锁鲜，口感嫩滑，你吃一口就知道。",
                "imgUrl": "https://website.hdlcdns.com/website/image/417d77ef9f214e86bbc281486a278f4c-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 89,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667194796643,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667194796641
            },
            {
                "id": 8247,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "红薯苕皮",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "纯红薯加工制成，软糯劲道，嚼劲十足。",
                "imgUrl": "https://website.hdlcdns.com/website/image/340447a28d4345b3b1de300f7ee1d361-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 90,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667194873110,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667194873109
            },
            {
                "id": 8248,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "一口爆浆奶酪鱼条",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "5成以上鱼肉混合鲜甜干酪炸至金黄，咬下一口先有鱼香、再有浓浓奶酪味。",
                "imgUrl": "https://website.hdlcdns.com/website/image/e3ff25ef4d73457aa46dc17abcc7f41d-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 91,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667195051217,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667195051216
            },
            {
                "id": 8249,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "葡萄油柑气泡水",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "葡萄加油柑，清爽解辣。",
                "imgUrl": "https://website.hdlcdns.com/website/image/e41e5db2e3cb4a16bfe9721fb42c5cec-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 92,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667195185400,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667195185399
            },
            {
                "id": 8250,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "山茶花香青柚茶",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "山茶花香浓郁，入口清甜。",
                "imgUrl": "https://website.hdlcdns.com/website/image/c6ae64cba90e49a9a402c4f5462ad51d-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 93,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1667195221376,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1667195221374
            }
        ]
    },
    "rc": 100000,
    "success": true
};

let sql = "insert into goods (g_id, g_dishName, g_dishDesc, g_imgUrl, g_createdTime, g_publishTime, g_Type,g_shopid) values ";
// sql = sql + "(" + shuancai.value.list[0].id +",'"+shuancai.value.list[0].dishName+"','"+shuancai.value.list[0].dishDesc+"','"+shuancai.value.list[0].imgUrl+"',"+shuancai.value.list[0].createdTime+","+shuancai.value.list[0].publishTime+","+"1"+","+"1"+"),";
let i=0;
for(;i<shuancai.value.list.length;i++){
    let j=9+i;
    sql = sql + "(" + j +",'"+shuancai.value.list[i].dishName+"','"+shuancai.value.list[i].dishDesc+"','"+shuancai.value.list[i].imgUrl+"',"+shuancai.value.list[i].createdTime+","+shuancai.value.list[i].publishTime+","+"2"+","+"1"+"),";
}
console.log(sql);