/**
 * @description: 特色蘸料
 * @param: g_Type-->4
 */
let tesezhanliao ={
    "msg": "成功",
    "value": {
        "pageNum": 1,
        "pageSize": 100,
        "total": 8,
        "pages": 1,
        "list": [
            {
                "id": 456,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "特色蘸料",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "锅底百搭",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/3245d784e99f4bbf9da8db3fb5052163-523-543.png,https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/934b7440ed8f4a109c711da1222157bb-621-446.jpg",
                "lastUpdatedTime": null,
                "orderNum": 31,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1600754905715,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1628832954313
            },
            {
                "id": 3325,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "鲜香味碟",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "提鲜必备",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/10053c392da7495d91af0d287e16fb1b-523-543.png,https://website.hdlcdns.com/website/image/ba903dbffe714332bd55acfe40077c16-621-372.JPG",
                "lastUpdatedTime": null,
                "orderNum": 32,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602235124324,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644387914550
            },
            {
                "id": 3594,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "香辣味碟",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "川渝搭档",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/26569279a2244f909914efa361c7b3d0-523-543.png,https://website.hdlcdns.com/website/image/16ba80a64e1b49a1ad796def3f007f78-621-420.jpg",
                "lastUpdatedTime": null,
                "orderNum": 33,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602828919067,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644387918211
            },
            {
                "id": 3595,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "海鲜味碟",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "海鲜专属",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/3e61fb1a7d7f4735bea5e2b093ecb778-523-543.png,https://website.hdlcdns.com/website/image/f16932aea39e449681bbfd5c9b734191-621-420.jpg",
                "lastUpdatedTime": null,
                "orderNum": 34,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602829005651,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644387923272
            },
            {
                "id": 3596,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "丸滑味碟",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "丸滑必备",
                "imgUrl": "https://website.hdlcdns.com/website/image/f1387fea632c417d89551ad97fab2b41-523-543.png,https://website.hdlcdns.com/website/image/be19f4f7c0da491e9fba6c0bc28771cf-621-298.jpg",
                "lastUpdatedTime": null,
                "orderNum": 35,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602829576327,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644387928190
            },
            {
                "id": 3597,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "酸辣味碟",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "酸辣开胃",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/a76c620af6a84e0091a36fd11e3fa513-523-543.png,https://website.hdlcdns.com/website/image/d4261c127e8843ad8a9ee1e5b608095a-621-452.jpg",
                "lastUpdatedTime": null,
                "orderNum": 36,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602829615118,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644387932498
            },
            {
                "id": 3598,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "蒜泥香油碟",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "川式口味",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/5bc97a0b65214482a8329f504c133392-523-543.png,https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/020a3cc53cd543f3b7b57db570236fc9-621-254.jpg",
                "lastUpdatedTime": null,
                "orderNum": 37,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602829648698,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1628832981986
            },
            {
                "id": 3599,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "芝麻调味酱",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "老北京口味",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/1a6322e3ea98448fa932a51ec445f27a-523-543.png,https://website.hdlcdns.com/website/image/0c17feffb5a94b1dbce6486b59732932-621-254.jpg",
                "lastUpdatedTime": null,
                "orderNum": 38,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602829679152,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1644387936870
            }
        ]
    },
    "rc": 100000,
    "success": true
}

let sql = "insert into goods (g_id, g_dishName, g_dishDesc, g_imgUrl, g_createdTime, g_publishTime, g_Type,g_shopid) values ";
// sql = sql + "(" + tesezhanliao.value.list[0].id +",'"+tesezhanliao.value.list[0].dishName+"','"+tesezhanliao.value.list[0].dishDesc+"','"+tesezhanliao.value.list[0].imgUrl+"',"+tesezhanliao.value.list[0].createdTime+","+tesezhanliao.value.list[0].publishTime+","+"1"+","+"1"+"),";
let i=0
for(;i<tesezhanliao.value.list.length;i++){
    let j=21+i;
    sql = sql + "(" + j +",'"+tesezhanliao.value.list[i].dishName+"','"+tesezhanliao.value.list[i].dishDesc+"','"+tesezhanliao.value.list[i].imgUrl+"',"+tesezhanliao.value.list[i].createdTime+","+tesezhanliao.value.list[i].publishTime+","+"4"+","+"1"+"),";
}
console.log(sql);