/**
 * @description: 特色饮品
 * @param: g_Type-->5
 */
let teseyinpin ={
    "msg": "成功",
    "value": {
        "pageNum": 1,
        "pageSize": 100,
        "total": 11,
        "pages": 1,
        "list": [
            {
                "id": 130,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "现炸酥肉",
                "menuName": null,
                "dishTag": "33",
                "dishDesc": "选用上等猪肉原料，酥脆可口，椒香口味给您不一样的体验！配上干辣椒碟或者番茄酱食用，风味独特，直接涮火锅食用也超赞哦。",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/764c43cebc394ac3bcc82dc10593ca59-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 2,
                "createdBy": null,
                "coverArea": null,
                "createdTime": 14,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1638416220749
            },
            {
                "id": 3604,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "茴香小油条",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "配以鲜茴香和茴香籽，口感松软，茴香味回味悠长，趁热吃外皮酥脆口感更佳。",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/e112fabae81e4e8da13afb0036735719-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 3,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602834619375,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1638416224705
            },
            {
                "id": 3608,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "五常米饭",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "黑土滋养，天池水灌溉，经过精细加工，淘洗，蒸煮而成，米粒晶莹饱满，香甜软糯。",
                "imgUrl": "https://hdl-globalportal-oss-bucket.oss-cn-beijing.aliyuncs.com/website/image/2dc70638c16e4c038a0e1cfcadad0866-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 7,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1602834777856,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1639655565394
            },
            {
                "id": 7714,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "酥酥嫩嫩炸牛奶",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "外面酥酥脆脆，内里绵软嫩滑，香甜适中，满口奶香。",
                "imgUrl": "https://website.hdlcdns.com/website/image/95052f1064ec4e7db6fced60b12bde23-396-543.jpg",
                "lastUpdatedTime": null,
                "orderNum": 8,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1647930070109,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1647933478358
            },
            {
                "id": 8321,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "一口爆浆奶酪鱼条",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "外酥里嫩 奶酪味十足。",
                "imgUrl": "https://website.hdlcdns.com/website/image/9c1da6d79cab4175ae66e63ea65f77ed-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 11,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673265345984,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673265345983
            },
            {
                "id": 8322,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "酥酥嫩嫩炸牛奶",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "口感酥脆，老少皆宜",
                "imgUrl": "https://website.hdlcdns.com/website/image/d35d1739a46a4db788aaa5bd830f2868-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 12,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673265412028,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673265412027
            },
            {
                "id": 8323,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "热卤大猪蹄子",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "卤香浓郁、肥而不腻、胶绵而不沾牙。",
                "imgUrl": "https://website.hdlcdns.com/website/image/ee640713616b4b7b9635e197bcf56a83-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 13,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673265435041,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673265435040
            },
            {
                "id": 8324,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "热卤耙鸡爪",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "卤香十足、口感软糯。",
                "imgUrl": "https://website.hdlcdns.com/website/image/64965852ec2b442c973cb778361311ee-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 14,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673265457126,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673265457124
            },
            {
                "id": 8325,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "热卤耙肥肠",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "口感劲道，卤味独特。",
                "imgUrl": "https://website.hdlcdns.com/website/image/41d044612a6e4088b16346b4b7ed3221-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 15,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673265525326,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673265525325
            },
            {
                "id": 8328,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "热卤大片素板筋",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "筋道弹韧 吮指回味（微辣）",
                "imgUrl": "https://website.hdlcdns.com/website/image/93cd4a3b0cc74c30ac7dd17b2289261d-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 16,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673931824153,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673931824151
            },
            {
                "id": 8329,
                "siteId": null,
                "country": null,
                "language": null,
                "parentMenuCode": null,
                "menuCode": null,
                "status": null,
                "flowStatus": null,
                "dishName": "热卤四大天王",
                "menuName": null,
                "dishTag": "",
                "dishDesc": "卤香浓郁、肥而不腻（微辣）",
                "imgUrl": "https://website.hdlcdns.com/website/image/259375dbcb854062b3a187deba56f09c-396-543.png",
                "lastUpdatedTime": null,
                "orderNum": 17,
                "createdBy": null,
                "coverArea": "",
                "createdTime": 1673931856153,
                "lastUpdatedBy": null,
                "childMenuCode": null,
                "optType": null,
                "publishTime": 1673931856152
            }
        ]
    },
    "rc": 100000,
    "success": true
};

let sql = "insert into goods (g_id, g_dishName, g_dishDesc, g_imgUrl, g_createdTime, g_publishTime, g_Type,g_shopid) values ";
// sql = sql + "(" + teseyinpin.value.list[0].id +",'"+teseyinpin.value.list[0].dishName+"','"+teseyinpin.value.list[0].dishDesc+"','"+teseyinpin.value.list[0].imgUrl+"',"+teseyinpin.value.list[0].createdTime+","+teseyinpin.value.list[0].publishTime+","+"1"+","+"1"+"),";
let i=0
for(;i<teseyinpin.value.list.length;i++){
    let temp = i+29;
    sql = sql + "(" + temp +",'"+teseyinpin.value.list[i].dishName+"','"+teseyinpin.value.list[i].dishDesc+"','"+teseyinpin.value.list[i].imgUrl+"',"+teseyinpin.value.list[i].createdTime+","+teseyinpin.value.list[i].publishTime+","+"5"+","+"1"+"),";
}
console.log(sql);