const goodtype = 
[
    {
        shopid:1,
        options:[
            {
                value:0,
                label:"全部"
            },
            {
                value:1,
                label:"锅底"
            },
            {
                value:2,
                label:"涮菜"
            },
            {
                value:3,
                label:"特色饮品"
            },
            {
                value:4,
                label:"特色蘸料"
            },
            {
                value:5,
                label:"小吃甜品"
            },
        ]
    },
    {
        shopid:2,
        options:[
            {
                value:10,
                label:"全部"
            },
            {
                value:6,
                label:"饮料"
            },
            {
                value:7,
                label:"美食"
            },
            {
                value:3,
                label:"特色饮品"
            },
            {
                value:8,
                label:"咖啡产品"
            },
            {
                value:9,
                label:"商品"
            },
        ]
    }
];

export default goodtype;